# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/elements.html

- name: article
  hint: true
  # unique: true
  ingredients:
    - role: topspace
      type: Select
      default: '0'
      settings:
        select_values: ['0', '1', '2', '3', '4', '5']
    - role: align
      type: Select
      settings:
        select_values: ['left', 'center', 'right']
    - role: headline
      type: Text
      default: :article_headline
      hint: true
    - role: picture
      type: Picture
      hint: true
      # settings:
      #   crop: true
    - role: text
      type: Richtext
      default: :article_text
      hint: true

- name: box_collection
  ingredients:
    - role: topspace
      type: Select
      default: '0'
      settings:
        select_values: ['0', '1', '2', '3', '4', '5']
    - role: box_align
      type: Select
      settings:
        select_values: ['left', 'center', 'right']
    - role: text_align
      type: Select
      settings:
        select_values: ['left', 'center', 'right']
    - role: headline
      type: Text
  nestable_elements:
    - box

- name: box
  hint: true
  unique: false
  ingredients:
    - role: headline
      type: Text
      default: :box_headline
      hint: true
    - role: picture
      type: Picture
      hint: true
      settings:
        # crop: true
    - role: text
      type: Richtext
      default: :article_text
      hint: true

- name: color_section
  ingredients:
    - role: topspace
      type: Select
      default: '0'
      settings:
        select_values: ['0', '1', '2', '3', '4', '5']
    - role: color
      type: Text
      settings:
        input_type: color

  nestable_elements:
    - article
    - box_collection

- name: bg_image_section
  ingredients:
    - role: topspace
      type: Select
      default: '0'
      settings:
        select_values: ['0', '1', '2', '3', '4', '5']
    - role: picture
      type: Picture
      hint: true
      settings:
        # crop: true
  nestable_elements:
    - article
    - box_collection