version: "3.8"
services:
  db:
    image: postgres:16.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms_development
  test-db:
    image: postgres:16.2
    volumes:
      - test-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms_test_db
volumes:
  db-data:
  test-db-data: